### PR TITLE
fix(ngx-forge): Added ngx-forge as a dependency

### PR DESCRIPTION
**Pull request by jyasveer**
Added ngx-forge as a dependency to automate the semantic release process

### CODE REVIEW

**Comment by jyasveer** [comment]
@joshuawilson can you please have a look ? Thanks

**Comment by joshuawilson** [comment]
It might work with the `-development` suffix on it. We can try. Is that something you can remove?

**Comment by jyasveer** [comment]
@joshuawilson  can you please check now ?

**Comment by joshuawilson** [comment]
You will need to update everyplace that uses it too.

**Pull request merged**
